logging:
    file: loadtest.log
    level:
        com:
            loadtest: DEBUG
        org:
            springframework: ERROR
    pattern:
        console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
        file: '%d %p %c{1.} [%t] %m%n'
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: itchtwo
        url: jdbc:h2:mem:loadtestdemo
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
